### ISSUE TITLE
How connect both serial port & CC Ease ?

### ISSUE THREAD

**Issue by ghost** [gieemek/ComfoAir_Binding_modified#1]
@gieemek Amazing job ! 
I found your code and your explanations extremely clear and simple.
Only one request: can you explain exactly how to connect the CC Ease and the serial port on the main board of the ConfoAir 350 ?
Thanks

**Comment by gieemek** [comment]
Hi,
CC Ease can not work with serial port pararelly: you have to choose CC Ease or serial, not both at the same time. You can switch between this connection with command "activate" : 0 = controlled by CC Ease, 1 = controlled by serial port (CC Ease is turned off).

If you write me your e-mail, I can send you some image how to connect serial cable between ComfoAir and PC.
Regards.

**Comment by ghost** [comment]
Hi, 
sure my email is servicedev***@gmail.com . 
My doubts are:
- how to connect serial cable beetween Confoair and PC, and 
- is possible keep attached simultaneously PC and CC Ease to Confoair, if yes how ? (I understood that one "software" client at time is allowed)

Regards

**Comment by gieemek** [comment]
Hello,
I send you few images to your email. how to connect ComfoAir serial port to controller (ie Raspberry Pi). Hope it is clear.

About control by CC Ease.
I understand you have ComfoAir unit with CC Ease and they works together.
You should leave this as it is - don't change anything.

To control by PC you need to connect between ComfoAir and PC by cable as I sent you in email.
After that install ComfoAir in openHAB PaperUI and create cfg file for it - you should set port in this file. You should have logs that connection is establish.
Create files (items, sitemaps and rule). You need items related to ComfoAir binding commands - you could control your ComfoAir by them. Please see at ComfoAir binding docs how to do it.

When you switch _Activate_ command to 1 ComfoAir will switch to listen from serial port and switch the CC Ease off. Sometime I need to switch it few times if ComfoAir is not responding.
Of course if you switch the _Activate_ command to 0 ComfoAir will turn the serial port off and turn the CC Ease on.

Wish you success.

**Comment by limes** [comment]
@gieemek Can you send me those pictures too? :) jakubowski@slawomir.info

**Comment by gieemek** [comment]
Cześć,
przepraszam, nie mam maila, który wysyłałem wcześniej. O ile dobrze
pamiętam wysyłałem rysunki, gdzie w ComfoAir należy podłączyć kabel do
sterowania. Przesyłam w załączniku.
Schemat kabla przyłączeniowego pokazuje podłączenie do Raspberry Pi. Jeżeli
sterowanie ma być z komputera PC, zamiast konwertera RS232 - UART trzeba
zastosować konwerter RS232 - USB i kabel USB wpiąć do komputera. Wówczas
konwerter zgłosi się na jakimś porcie COM (COM1 albo COM2, albo inny numer)
i ten port trzeba ustawić w openHABie.

Jeśli będziesz potrzebował jeszcze jakiś informacji, to służę pomocą.
Miłej zabawy, Grzegorz Miąsko
[image: ComfoAir-plytaPrzylaczeniowa.jpg]
[image: ComfoAir-płyty.jpg]
[image: ComfoAir-PC_podlaczenie.jpg]

śr., 4 gru 2019 o 11:43 Sławomir Jakubowski <notifications@github.com>
napisał(a):
