### ISSUE TITLE
How is the Exhaust&Supply, Supply only and Exhaust only mode controlled

### ISSUE THREAD

**Issue by adorobis** [gieemek/ComfoAir_Binding_modified#2]
Hello, I'm trying to figure out how the control of the fan mode is controlled on the recu unit. I could not find a relevant command in the comfoair protocol documentation, neither in the definition of the commands in your binding. Could you please help understanding it? I'm working on integrating the Comfoair device with Home Assistant.

**Comment by gieemek** [comment]
Hello,
very sorry for my long delay.
I think you are looking for commands: _fan_out_0_ - 3 and _fan_in_0_ - 3. This commands are for setting the  fan rotation on each level of ventilation. Allowable values (in percent) you can find in the documentation of ComfoAir binding or in the user guide of your device.
If you want to change level of ComfoAir you should use _fan_level_ command.
Once again sorry for delay. Good luck.

**Comment by adorobis** [comment]
Thanks! That's what I was afraid of, not very elegant solution. Will implement it in free time :)
