### ISSUE TITLE
Filter reset command does not reset filter hours

### ISSUE THREAD

**Issue by adorobis** [gieemek/ComfoAir_Binding_modified#5]
Hello,
I'm using this method to control the Comfo Air 350 unit and all works great except the function to reset the filter status. It resets it but after an hour it goes back to the filter full status. When digging deeper I've noticed that it does not reset the filter hours counter (available via command xDB) so when it increases by one hour the filter goes to full status again. Any idea what could be wrong or how to fix it?

**Comment by gieemek** [comment]
Hi,
Are you using openHAB to control your comfoair ? What binding version 1.x or 3.x ?

**Comment by adorobis** [comment]
No, I'm using home assistant and my own python integration but I'm using exactly the same commands and was wondering if anybody has faced similar issue here.

**Comment by gieemek** [comment]
Hello,
sorry for delay.
Yes, the similar problem was discussed in this thread:
https://community.openhab.org/t/solved-comfoair-add-filter-reset-in-binding/25337/30?page=2
at it's end, but it was not solved.
Do you have any responses from comfoair ? If I can look at them, maybe I could help.

**Comment by adorobis** [comment]
No problem, it is not an urgent issue.
The response is correct ACK message (as per docu only ACK should be returned): `\x07\xf3`
By reading above thread I could not figure out if there was a solution found :) Was it?

**Comment by gieemek** [comment]
No, the problem with filter reset was not solved (Matthias was stoped answer).
I assume that:

- you switch off CCEase when you control comfoair by HA,
- your request are correct, because you get proper response,
- all other commands work properly.

Proper request to comfoair to reset filter should be:
07 f0 00 db 08 00 00 00 01 00 00 00 00 91 07 0f

My questions:
Why your filter state come back to full value after 1 hour (not immediately) ? Do you send request for data hourly ?

openHAB binding sends request for data after changing (request for changing data, receive ack, request for data, receive ack). In this way binding knows current value of data from comfoair.
Does your python script work like this ?

**Comment by adorobis** [comment]
> I assume that:
> 
> * you switch off CCEase when you control comfoair by HA,
> * your request are correct, because you get proper response,
> * all other commands work properly.

That is correct. Only the resetting filter does not work as expected.

> Proper request to comfoair to reset filter should be:
> 07 f0 00 db 08 00 00 00 01 00 00 00 00 91 07 0f

Yes, I'm sending exactly this command.

> Why your filter state come back to full value after 1 hour (not immediately) ?

I think that it resets to full after filter hours counter increases by 1, which takes up to 1 hour.

> Does your python script work like this ?

And yes, I'm doing exactly the same thing - when changing something I'm right after reading current state of the comfoair - only those parameters which are being changed - so after filter reset I'm reading filter status, filter weeks (this is a config param) and filter hours - the last one I think should be reset to 0 but isn't.

**Comment by gieemek** [comment]
One idea:
try this request to comfoair:
07 f0 00 db 04 00 00 00 01 8d 07 0f

because I'm not sure if data block should have 8 bytes or 4 bytes only (command db has 4 bytes only).

**Comment by adorobis** [comment]
Ah, sorry, my command is actually 4 bytes only, so it is `07 f0 00 db 04 00 00 00 01 8d 07 0f`

**Comment by gieemek** [comment]
Please check if "_filter hours_" is reset after your "_filter reset_" to comfoair (read this parameter from comfoair). Should be 0.

**Comment by adorobis** [comment]
I've checked and it is not getting reset to 0 (value does not change), although filter status changes to clean (and back to full when filter hours increases by 1).

**Comment by gieemek** [comment]
I'm afraid it is bug in comfoair software.
If your filter error status is reset, your filter hours should be changed to 0 .
My software version is 3.30.

So how you reset this value in comfoair ? by CCEase ?

**Comment by adorobis** [comment]
> If your filter error status is reset, your filter hours should be changed to 0 .

Yes, that's what I would expect


> My software version is 3.30

You mean the comfoair firmware out the binding? 



> So how you reset this value in comfoair ? by CCEase ?

Well, I have the comfosense controller but not connected anymore, the CCEase got broken some time ago...

**Comment by gieemek** [comment]
> My software version is 3.30.

It is my firmware of comfoair unit.

> Well, I have the comfosense controller but not connected anymore, the CCEase got broken some time ago...

So you can't reset filter hours at all.

**Comment by gieemek** [comment]
One more idea.
I hope it is possible to simulate CCEase control. I have never tried but it should work.

You can use x37 command which means pressing the button of CCEase.
Filter error is reset by pressing modus button by 2 sec.
So try to send request to comfoair like this:
`07 f0 00 37 07 00 82 00 00 00 00 00 6d 07 0f`
Number 82 in the second byte of data block means pressing the modus button by 2080 milisec.
The correct answer from comfoair is `x00 x3C`

I am very interesting if this works.

**Comment by adorobis** [comment]
Many thanks for ideas! Will give it a try and report back the outcome :)

**Comment by adorobis** [comment]
> So try to send request to comfoair like this:
> `07 f0 00 37 07 00 82 00 00 00 00 00 6d 07 0f`

Bingo! This works and the filter hours have been now reset to 0. I'll try again after some hours once this counter increases again, but looks good so far. Many thanks for your help! This is contribution to [Home Assistant integration](https://github.com/adorobis/hacomfoairmqtt) (although I'm not strong enough to build it as official integration - only RS232 to MQTT python script).

**Comment by gieemek** [comment]
Gratuluję, super, że się udało.

**Comment by adorobis** [comment]
Wielkie dzięki za pomoc!

**Comment by adorobis** [comment]
@gieemek one more question: one last feature I could not find in the protocol documentation is the ability to enable only exhaust, only intake or both fans. This worked on CCEase and Comfosense controllers by pressing 
![image](https://user-images.githubusercontent.com/19752098/151247393-c4ff28d2-4f92-4f91-9a76-ba15b79b6eb1.png)
button. Have you implemented it in your integration/binding?

**Comment by gieemek** [comment]
No, it is not possible to implement this function. I have done it by script - it is very complicated.
But you can use the same command as for reset filter error with shorter time (decrease second byte of data block). I have not thought about it earlier.

**Comment by adorobis** [comment]
So far no success, will play with it a bit more in free time.
